[window]
opacity = 1
decorations = "Full"

[window.padding]
x = 8
y = 8

[font]
size = 11.0

[font.normal]
family = "GeistMonoNerdFont"
style = "Regular"

[font.bold]
family = "GeistMonoNerdFont"
style = "Bold"

[font.italic]
family = "GeistMonoNerdFont"
style = "Italic"

[cursor]
blink_interval = 500

[cursor.style]
shape = "Block"
blinking = "Off"

[colors.primary]
background = "#1d1d1d"
foreground = "#fafafa"

[colors.cursor]
text = "#242424"
cursor = "#ebebeb"

[colors.selection]
text = "#242424"
background = "#ebebeb"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true


[colors.normal]
black = "#110F18"
red = "#FF6767"
green = "#61FFCA"
yellow = "#FFCA85"
blue = "#A277FF"
magenta = "#A277FF"
cyan = "#61FFCA"
white = "#EDECEE"
